# Generated by Django 3.2.9 on 2022-03-06 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20220306_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='children',
        ),
    ]
