# Generated by Django 3.2.9 on 2022-03-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_alter_topic_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_level',
            field=models.IntegerField(choices=[(1, 'LEVEL1'), (2, 'LEVEL2'), (3, 'LEVEL3'), (4, 'LEVEL4')], default=1),
        ),
    ]
